backend:
  name: github
  repo: ordidxzero/tech-blog
media_folder: static/images
public_folder: /images
collections:
  - name: posts
    label: Post
    folder: posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path, required: false }
      - { name: prevStep, label: Previous Step, widget: select, multiple: true, options: [Post01, Post04] }
      - { name: category, label: Category, widget: select, multiple: true, options: [theory, book, project], default: [project] }
      - { name: tags, label: Tags, widget: list, multiple: true, options: [javascript, nodejs, pug, typescript, tensorflow, ai] }
      - { name: body, label: Body, widget: markdown }
